export const GAME_CONFIG = {
  MIN_TIME: 0,
  MAX_TIME: 59,
  MAX_MINUTES: 600,
  LOW_TIME_THRESHOLD: 30,
  SPLASH_DURATION: 3000,
  DEBOUNCE_DELAY: 300,
  CARD_FLIP_DURATION_MS: 225,
  SPREAD_STAGGER_MS: 100,
} as const
